### ISSUE TITLE
API reference is incomplete

### ISSUE THREAD

**Issue by thdoan** [DataGridXL/DataGridXL2#116]
In the Playground I see this for the "no headers" example:

```
var options = {
	showColHeaders: false,
	showRowHeaders: false
};
```

However, I see no mention of the `showColHeaders` or `showRowHeaders` options in the API reference.

**Comment by DataGridXL** [comment]
Hi,

Thanks for letting us know. We're aware of it. We're working on version 3 of DataGridXL which will have extensive auto-generated API documentation straight from the source code, so that won't happen with the new version.

As far as DGXL2 goes, we won't be updating the API pages. But if you any questions about its API or something is not clear in the docs, please reach out to us at support@datagridxl.com

**Comment by thdoan** [comment]
Thanks for the reply, @DataGridXL. Can't wait to see v3!

**Comment by DataGridXL** [comment]
Beta screenshot:

![Screenshot 2024-04-25 13 46 35](https://github.com/DataGridXL/DataGridXL2/assets/67742466/3a23601c-ab2e-454f-8505-670be891de30)

Version 3 will introduce filters, multi-column sorting, cell graphics, cell validation, while keeping its trademark performance.
